### PR TITLE
Feature/dot name support

### LINKED ISSUE #96: Adjust JSON ingestion to work with .js files in new format
We have a new format to ingest, where the files have a slightly different type of format:

Mock-up example:
* filename: ```file-name.js````
* format

```
window.ABC.data_type_name.part0 = [
  {
    "fieldName1" : {
      "fieldName1a" : "12345678",
      "fieldName1b" : "text"
    }
  }
]
``` 
I'll send an example file offline.

### PR DESCRIPTION
**Pull request by bobvdvelde**
# Support for global keys that include '.' 

## Closes #96 
____

* Separated js files for easier testing
* created tests for file and object parsing using jest
* created testcases for files that include a `.` in the global key
* implemented JSON parsing using `jsonPath` 
* created sample generator for short messages with a `.` in global key
* generated new sample data 

## Assumptions

* we expect `.` only in the global keys, not in object keys

## Usage / Minimal Example

osd2f_upload_with_dot_in_global_name

Instructions on how to verify changes this PR by running code

1. See the new [default config](https://github.com/uvacw/osd2f/blob/feature/dot-name-support/osd2f/settings/default_upload_settings.yaml)

2. Start a server 
```bash
OSD2F_SECRET=secret \
OSD2F_BASIC_AUTH="user;pass" \
OSD2F_MODE=Development \
osd2f -m Development
```
3. upload the new sample content
4. investigate the `messages.json` result

## Checklist
- [X] Added tests if appropriate (and it should always be)
- [X] Created new issues when required

### CODE REVIEW

**Comment by theoaraujo** [comment]
Looks good! A few items, added as separate comments:

- [ ] Elements from a list inside dictionary (second level) disappear
image
image
image

**Comment by theoaraujo** [comment]
- [ ] An empty column appears with for the first level of information (e.g., information), while only the third level is being asked for in the config file
image
image

**Comment by theoaraujo** [comment]
Having some trouble with files that start with a format as 
```
key.key2.key3.key4 = [
  { key5 : { realkeywewant: "valueweneed" } ]
```
Sent message asking for more context

**Review by theoaraujo — CHANGES_REQUESTED** [review]
Format covered in #96 does not seem to work. Please see other comments in further testing (if some of them are not relevant here, then we can open new tickets).

**Comment by bobvdvelde** [comment]
> * [ ]  The level being asked in the configuration file does not seem to match the level in the table. For example, config file has `information.post.post_metadata.expanded_url` as a field requested. The field does appear in the data, but as an element inside a column for a level higher (information.post) - instead of as a separate column in the table
> 
> image

I believe this is because it's an array value, which up to now have always been bundled. Basically, each entry has multiple values, in this particular case, every post has multiple information.post values. Each is whitelist-parsed and appears in the same row in the table. 

We can unbundle these into separate columns with some hacking or create nested tables but neither strike me as elegant solutions.

**Comment by bobvdvelde** [comment]
> Format covered in #96 does not seem to work. Please see other comments in further testing (if some of them are not relevant here, then we can open new tickets).

Added parsing for invalid JSON in the particular style of Twitter.

**Comment by bobvdvelde** [comment]
I've fixed bugs:
* arrays of string values (e.g. `[ "foo", "bar"]` ) are no longer converted to a list of empty objects (e.g. `[{},{}]`)
* partial path matches (e.g. ` field : [] ` when looking for `field.subfield`) are no longer included
* Twitter style bad json (e.g. `data = [ { "obj" : 1}, {"obj" : 2}]` ) are now parsed by assuming only the original `in_field` key is badly formed. This is testable by uploading a badly formatted version of the mock data short messages file (save this to `messages.json` and upload it on the [upload page](http://localhost:5000/upload)):
```text
messages.collection = [
  {
    "id": "41235082236765",
    "message": "Enter own sure traditional white this. Point dark could gas mention speech. Reveal all laugh son right."
  },
  {
    "id": "149224703736780",
    "message": "Oil there support month away skin hold."
  }
]
``` 
which should register the two messages contained therein.

Things for (possibly) later:
* the remark about nested objects not getting separate columns. As an entry that has a nested field, such as:
```json
{
  "field" : [ 
    { "subfield" : "value 1" },
    { "subfield" : "value 2"},
  ]
}
``` 
now appears on one row in the table. Other options are possible, but are probably best considered as separate functionality.

**Comment by bobvdvelde** [comment]
Some additional fixes for Twitter content:
* twitter provides javascript files instead of JSON. This contains unescaped `\` characters. These are now properly escaped before parsing
* JS files can be in UTF16, now we check whether a file introduces bad characters on decoding it from UTF8->UTF16 and fall back to the non-decoded version if a bad character is introduced
* there was a bug in which multi-nested fields (e.g. `field.nested.doublenested`) did not parse correctly, this is now fixed. 

Example specifications for twitter files:

```yaml
# default_upload_settings.yaml
files:
  'ad-impressions.js':
    in_key: window.YTD.ad_impressions.part0
    accepted_fields:
      - ad.adsUserData.adImpressions.impressions.deviceInfo.osType

  like.js:
    in_key: window.YTD.like.part0
    accepted_fields:
      - like.tweetId
      - like.fullText

  tweet.js:
    in_key: window.YTD.tweet.part0
    accepted_fields:
      - tweet.entities.user_mentions.name
```

**Comment by bobvdvelde** [comment]
@theoaraujo could you review the changes?

**Comment by theoaraujo** [comment]
This is working much better, but there's apparently still one last issue with the pattern Dictionary - Dictionary - List.

image



For example:
* ```tweet.entities.user_mentions``` shows data in the table
* ```tweet.entities``` appears empty

The same issue is happening in other places, e.g., ad-engagements (```ad.adsUserData.adEngagements``` comes in empty, but ```ad.adsUserData.adEngagements.engagements``` shows info).

Could you please check?

**Review by theoaraujo — CHANGES_REQUESTED** [review]
Almost there, but please see comment I added.

**Review by theoaraujo — APPROVED** [review]
Great! All seems to work now.

**Pull request merged**
